# Generated by Django 4.2.6 on 2023-11-18 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commentaire',
            table='commentaire',
        ),
        migrations.AlterModelTable(
            name='film',
            table='films',
        ),
        migrations.AlterModelTable(
            name='nlp',
            table='nlp',
        ),
    ]
