# Generated by Django 4.2.6 on 2023-11-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0002_alter_commentaire_table_alter_film_table_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentaire", name="pseudo", field=models.TextField(null=True),
        ),
    ]
