# Generated by Django 4.2.6 on 2023-11-25 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0003_commentaire_pseudo"),
    ]

    operations = [
        migrations.RemoveField(model_name="commentaire", name="note_dislike",),
        migrations.RemoveField(model_name="commentaire", name="note_like",),
    ]
