# Generated by Django 4.2.6 on 2023-11-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0004_remove_commentaire_note_dislike_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentaire",
            name="titre_film",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
