# Generated by Django 4.2.6 on 2023-11-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0005_commentaire_titre_film"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentaire", name="note", field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="film", name="note_presse", field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="film", name="note_spectateur", field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="nlp", name="note", field=models.FloatField(),
        ),
    ]
