# Generated by Django 4.2.6 on 2023-11-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0006_alter_commentaire_note_alter_film_note_presse_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="nlp", name="film",),
        migrations.AddField(
            model_name="nlp",
            name="titre_film",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
